# Generated by Django 4.1.13 on 2026-02-05 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('banking_core', '0002_alter_account_id_alter_referenceid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referenceid',
            name='id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, db_column='_id', primary_key=True, serialize=False),
        ),
    ]
